version: "3.9"
services:
  db:
    image: mariadb:10
    volumes:
      - ./data/db:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./data/web:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  keycloak:
    image: jboss/keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: 123456
    ports:
      - 8080:8080
    depends_on:
      - db

